### PR TITLE
adding noReset() button

### PR DESCRIPTION
**Pull request by mikeysklar**
The Adafruit boards with co-processor (PyPortal, MatrixPortal M4, Metro Airlift and related variants) running passthru code will not connect over serial if reset. This small update adds a small button called "Connect without Reset". 

The has been tested with a PyPortal and Feather ESP32-S3. It was working as expected.

### CODE REVIEW

**Comment by mikeysklar** [comment]
@dhalbert

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks very much for working on this!

I think it would be good to add a little immediate documentation next to the switch, something like `Turn on for pass-through updates`, `Use for pass-through updates`, or similar. It could be part of the `<label>` or it could be a separate `<div>` or `<p>` in the immediate surrounding `<div>`.

**Comment by mikeysklar** [comment]
Good thought. The "no reset" on/off logic is confusing for multiple reasons even though it matches the CLI. I'll update the wording.

**Comment by dhalbert** [comment]
> The "no reset" on/off logic is confusing for multiple reasons even though it matches the CLI. I'll update the wording.

I was thinking about whether it's kind of a double negative ("enable/disable no reset"). Should the switch be reset off/on, and default to on instead? But that's not so easy to explain either.

**Review by dhalbert — APPROVED** [review]
I was wondering if we should mention what the switch does, but maybe that is Too Much Information, especially for novice users. I think this is good; thanks very much for this fix!

**Pull request merged**
